<?php

require 'weltz_dbconnect.php';
require '../vendor/autoload.php'; // Load TCPDF

if (!isset($_GET['referenceNum'])) {
    die('Reference number missing.');
}

$referenceNum = $_GET['referenceNum'];

// Fetch order details, including customer name
$orderSQL = "SELECT o.createdAt, COALESCE(CONCAT(u.userFname, ' ', u.userLname), 'Deleted User') AS userFullName  
             FROM orders_tbl o 
             JOIN users_tbl u ON o.userID = u.userID 
             WHERE o.referenceNum = ?";
$stmt = $conn->prepare($orderSQL);
$stmt->bind_param("s", $referenceNum);
$stmt->execute();
$order = $stmt->get_result()->fetch_assoc();

if (!$order) {
    die('Order not found.');
}

$orderDate = date("F j, Y, g:i A", strtotime($order['createdAt']));
$customerName = $order['userFullName'];

// Fetch order items
$orderItemsSQL = "SELECT p.productName, oi.orderItemQuantity, oi.orderItemTotal 
                  FROM order_items_tbl oi
                  JOIN products_tbl p ON oi.productID = p.productID
                  JOIN orders_tbl o ON oi.orderID = o.orderID
                  WHERE o.referenceNum = ?";
$stmt = $conn->prepare($orderItemsSQL);
$stmt->bind_param("s", $referenceNum);
$stmt->execute();
$orderItems = $stmt->get_result();

// Create PDF
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Weltz Industrial Phils INC.');
$pdf->SetTitle("Invoice #$referenceNum");
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->AddPage();

// Company Logo
$logo = '../assets/weltz_logo.png';
$pdf->Image($logo, 15, 10, 40, 20);

// Company Info
$pdf->SetFont('helvetica', 'B', 16);
$pdf->SetXY(60, 10);
$pdf->Cell(140, 10, 'Weltz Industrial Phils INC.', 0, 2, 'R');
$pdf->SetFont('helvetica', '', 11);
$pdf->SetX(60);
$pdf->Cell(140, 6, 'Vista Verde Executive Village, Cainta Rizal 1900', 0, 2, 'R');
$pdf->SetX(60);
$pdf->Cell(140, 6, 'Email: weltzphils@gmail.com | Phone: +63 960 275 8956', 0, 2, 'R');

// Line separator
$pdf->Ln(5);
$pdf->Line(10, 35, 200, 35);
$pdf->Ln(10);

// Invoice Title
$pdf->SetFont('helvetica', 'B', 14);
$pdf->Cell(190, 10, "INVOICE", 0, 1, 'C');
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(190, 6, "Invoice #: $referenceNum", 0, 1, 'C');
$pdf->Cell(190, 6, "Date Issued: $orderDate", 0, 1, 'C');
$pdf->Ln(8);

// Customer Info
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(30, 7, "Billed To:", 0, 1);
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(100, 7, $customerName, 0, 1);
$pdf->Ln(5);

// Table Headers
$pdf->SetFillColor(220, 53, 69); // Bootstrap Red
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 11);
$pdf->Cell(110, 8, 'Product Name', 1, 0, 'C', true);
$pdf->Cell(30, 8, 'Quantity', 1, 0, 'C', true);
$pdf->Cell(50, 8, 'Total Price', 1, 1, 'C', true);

// Table Rows
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 10);
$fill = false;
$totalAmount = 0;

while ($row = $orderItems->fetch_assoc()) {
    $pdf->SetFillColor(245, 245, 245);
    $pdf->Cell(110, 8, $row['productName'], 1, 0, 'L', $fill);
    $pdf->Cell(30, 8, $row['orderItemQuantity'], 1, 0, 'C', $fill);
    $pdf->Cell(50, 8, 'PHP ' . number_format($row['orderItemTotal'], 2), 1, 1, 'R', $fill);
    $fill = !$fill;
    $totalAmount += $row['orderItemTotal'];
}

// Total Row
$pdf->SetFont('helvetica', 'B', 11);
$pdf->SetFillColor(52, 58, 64); // Dark Gray
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(140, 10, 'Grand Total', 1, 0, 'R', true); // 110 + 30 = 140
$pdf->Cell(50, 10, 'PHP ' . number_format($totalAmount, 2), 1, 1, 'R', true);

// Footer Notes
$pdf->Ln(15);
$pdf->SetFont('helvetica', '', 9);
$pdf->SetTextColor(100, 100, 100);
$pdf->Cell(0, 5, 'Thank you for your business!', 0, 1, 'C');
$pdf->Cell(0, 5, 'This invoice was generated by Weltz Industrial Phils INC.', 0, 1, 'C');
$pdf->Cell(0, 5, 'Please contact us for any billing concerns.', 0, 1, 'C');

// Output PDF
$pdf->Output("Invoice_$referenceNum.pdf", 'D');
?>
